---
- name: Install postgre via curl from root
  shell: rpm -Uvh https://yum.postgresql.org/11/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  become: true

- name: Install PostgreSQL and requirements
  yum:
    name: [
      python-psycopg2,
      postgresql11,
      postgresql11-libs,
      postgresql11-server,
      postgresql11-contrib
    ]
    state: present

- name: Make sure configuration directory exists
  file:
    path: /var/lib/pgsql/11/data
    state: directory
    owner: postgres
    group: postgres

- name: Create PostgreSQL database cluster
  command: /usr/pgsql-11/bin/postgresql-11-setup initdb

- name: Copy PostgreSQL configuration files
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items:
    - {
        src: pg_hba.conf.j2,
        dest: /var/lib/pgsql/11/data/pg_hba.conf,
        mode: "0600",
        owner: postgres,
        group: postgres
      }
    - { 
        src: postgresql.conf.j2,
        dest: /var/lib/pgsql/11/data/postgresql.conf,
        mode: "0600",
        owner: postgres,
        group: postgres
       }
              
- name: Start and enable PostgreSQL service
  service:
    name: postgresql-11
    state: started
    enabled: true
