- name: "Install forever (to run Node.js app)."
  npm:
  args:
    name: forever 
    global: yes 
    state: present

- name: "Check list of Node.js apps running."
  command: forever list
  register: forever_list
  changed_when: false


- name: "Start the Node app"
  shell: forever --minUptime 5000 --spinSleepTime 20000 start -c "npm start" src
  args:
    chdir: /vagrant