- hosts: server
  become: true
  vars_files:
    - "vars/common.yml"
    - "vars/environments/{{ environment_id }}.yml"
    - "{{ secrets_file_path }}"
  roles:
    - os-setup
    - Curl_nodejs
    - yum_nodejs
    - apache-install
    # - shibboleth-install
    - apache-config
    - postgres-install
    - postgres-data
    - justus-backend
    - firewall
    # - npm-run-build
    - postgres-session
    - Install-Epel-Release
    - Install-Redis
    - npm-start