- hosts: server
  become: true
  vars_files:
    - "vars/common.yml"
    - "vars/environments/{{ environment_id }}.yml"
    - "{{ secrets_file_path }}"
  roles:
    - os-setup
    - php-install
    - apache-install
    # - shibboleth-install
    - apache-config
    - postgres-install
    - postgres-data
    - justus-backend
    - firewall