---
- name: Install Samba
  yum:
    name: samba
    state: installed

- name: Configure Samba
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644

- name: Create Samba users if they don't exist yet
  shell: >
    (pdbedit --user={{ item.name }} 2>&1 > /dev/null) \
    || (echo {{ item.password }}; echo {{ item.password }}) \
    | smbpasswd -s -a {{ item.name }}
  with_items: [
      { name: "vagrant", password: "vagrant" }
  ]
  no_log: true
  register: create_user_output
  changed_when: "'Added user' in create_user_output.stdout"
